### ISSUE TITLE
Add 'Track difficulty by Tier' filter

### ISSUE THREAD

**Issue by rhombus9** [wowvv0w/djmax-random-selector-v#10]
설정한 래더 티어에 맞춰서 난이도 범위를 조정해주는 필터가 있으면 편할것 같습니다.

**Comment by wowvv0w** [comment]
래더 티어에 따른 난이도 범위는 시즌에 따라 변동될 가능성이 있습니다. 그러므로 어플리케이션에 필터를 따로 추가하는 대신 QueryFilter의 프리셋 기능을 이용해서 배포 시 기본 프리셋 파일로 제공하겠습니다.
