### ISSUE TITLE
선곡기 재시작시 레벨 강제 통일

### ISSUE THREAD

**Issue by hunt3rwho** [wowvv0w/djmax-random-selector-v#8]
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/47919334/205291933-775d2332-b62b-4d2e-9644-50ebfab232c1.png">

<img width="1920" alt="2" src="https://user-images.githubusercontent.com/47919334/205291943-ec6f39db-d6f3-418d-b316-2abe710c8a84.png">

1번상태 처럼 일반 난이도와 sc난이도 다르게 설정 후 끄고 재시작 하면 2번 상태처럼 두개의 난이도가 강제로 통일 되어있습니다.

**Comment by wowvv0w** [comment]
해당 이슈를 해결한 1.5.1 버전을 게시하였습니다. 제보 감사합니다.
